apiVersion: v1
kind: Service
metadata:
  name: tppbe
  labels:
    app: tppbe
spec:
  ports:
  - port: 5001
    name: be
  clusterIP: None
  selector:
    app: tppbe
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tppbe
spec:
  selector:
    matchLabels:
      app: tppbe # has to match .spec.template.metadata.labels
  serviceName: "tppbe"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: tppbe # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tppbe
        image: dengol/betpp-app:1.0.0
        ports:
        - containerPort: 5001
          name: tppbe
        env:
        - name: DB_HOST
          value: "tppdb"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "postgres"
        - name: ENVIRONMENT
          value: "prod"