apiVersion: v1
kind: Service
metadata:
  name: tppfe-external
  labels:
    app: tppfe  # Adjust this to match your app's label if needed
spec:
  selector:
    app: tppfe  # Adjust this to match your app's label if needed
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081  # This port will be exposed on all nodes
  type: NodePort
